// Package moexoptcalc provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package moexoptcalc

// Defines values for AssetSubtype.
const (
	AssetSubtypeCommodity AssetSubtype = "commodity"
	AssetSubtypeCurrency  AssetSubtype = "currency"
	AssetSubtypeIndex     AssetSubtype = "index"
	AssetSubtypeShare     AssetSubtype = "share"
)

// Defines values for AssetType.
const (
	AssetTypeCommodity AssetType = "commodity"
	AssetTypeCurrency  AssetType = "currency"
	AssetTypeFutures   AssetType = "futures"
	AssetTypeIndex     AssetType = "index"
	AssetTypeShare     AssetType = "share"
)

// Defines values for IndicatorType.
const (
	Delta         IndicatorType = "delta"
	Gamma         IndicatorType = "gamma"
	ProfitAndLoss IndicatorType = "profit_and_loss"
	Rho           IndicatorType = "rho"
	Theta         IndicatorType = "theta"
	Vega          IndicatorType = "vega"
)

// Defines values for OptionSeriesType.
const (
	M OptionSeriesType = "M"
	Q OptionSeriesType = "Q"
	W OptionSeriesType = "W"
)

// Defines values for OptionType.
const (
	Call OptionType = "call"
	Put  OptionType = "put"
)

// Defines values for SimulatedPositionType.
const (
	SimulatedPositionTypeCommodity SimulatedPositionType = "commodity"
	SimulatedPositionTypeCurrency  SimulatedPositionType = "currency"
	SimulatedPositionTypeFutures   SimulatedPositionType = "futures"
	SimulatedPositionTypeOption    SimulatedPositionType = "option"
	SimulatedPositionTypeShare     SimulatedPositionType = "share"
)

// Asset Базовый актив
type Asset struct {
	// AssetCode Торговый код базового актива
	AssetCode string `json:"asset_code"`

	// AssetSubtype Подтип базового актива - фьючерса
	AssetSubtype *string `json:"asset_subtype,omitempty"`

	// AssetType Тип базового актива
	AssetType string `json:"asset_type"`

	// Title Наименование базового актива
	Title string `json:"title"`
}

// AssetSubtype Подтип фьючерса (базового актива)
type AssetSubtype string

// AssetType Тип базового актива
type AssetType string

// CalculatedPortfolio Рассчитанный опционный портфель
type CalculatedPortfolio struct {
	// InitialMargin  Рассчитанное значение гарантийного обеспечения
	InitialMargin *float64 `json:"initial_margin,omitempty"`

	// Positions Рассчитанные позиции
	Positions []CalculatedPosition `json:"positions"`

	// Total Всего
	Total CalculatedTotal `json:"total"`
}

// CalculatedPosition Рассчитанные показатели
type CalculatedPosition struct {
	// DaysUntilExpiring Дней до экспирации
	DaysUntilExpiring *int `json:"days_until_expiring,omitempty"`

	// Delta Дельта, пунктов
	Delta *float64 `json:"delta,omitempty"`

	// ExpirationDate Дата погашения
	ExpirationDate *Date `json:"expiration_date,omitempty"`

	// Expired Признак экспирации фьючерса/опциона
	Expired *bool `json:"expired,omitempty"`

	// Fee Комиссия, руб
	Fee *float64 `json:"fee,omitempty"`

	// Gamma Гамма, пунктов
	Gamma *float64 `json:"gamma,omitempty"`

	// Price Цена покупки
	Price *float64 `json:"price,omitempty"`

	// ProfitAndLoss Прибыль/убыток, пунктов
	ProfitAndLoss *float64 `json:"profit_and_loss,omitempty"`

	// ProfitAndLossRub Прибыль/убыток, руб
	ProfitAndLossRub *float64 `json:"profit_and_loss_rub,omitempty"`

	// Quantity Количество покупки (отрицательное число - продажа)
	Quantity int `json:"quantity"`

	// Rho Ро, пунктов
	Rho *float64 `json:"rho,omitempty"`

	// Secid Торговый код опциона
	Secid string `json:"secid"`

	// Strike Cтрайк
	Strike *float64 `json:"strike,omitempty"`

	// Theorprice Теор цена, пунктов
	Theorprice *float64 `json:"theorprice,omitempty"`

	// Theta Тета, пунктов
	Theta *float64 `json:"theta,omitempty"`

	// Type Вид торгового инструмента
	Type SimulatedPositionType `json:"type"`

	// Vega Вега, пунктов
	Vega *float64 `json:"vega,omitempty"`

	// Volatility Волатильность, процентов
	Volatility *float64 `json:"volatility,omitempty"`
}

// CalculatedTotal Рассчитанные суммарные показатели
type CalculatedTotal struct {
	// Delta Дельта, пунктов
	Delta *float64 `json:"delta,omitempty"`

	// Fee Комиссия, руб
	Fee *float64 `json:"fee,omitempty"`

	// Gamma Гамма, пунктов
	Gamma *float64 `json:"gamma,omitempty"`

	// ProfitAndLoss Прибыль/убыток, пунктов
	ProfitAndLoss *float64 `json:"profit_and_loss,omitempty"`

	// ProfitAndLossRub Прибыль/убыток, руб
	ProfitAndLossRub *float64 `json:"profit_and_loss_rub,omitempty"`

	// Rho Ро, пунктов
	Rho *float64 `json:"rho,omitempty"`

	// Theta Тета, пунктов
	Theta *float64 `json:"theta,omitempty"`

	// Vega Вега, пунктов
	Vega *float64 `json:"vega,omitempty"`
}

// Futures Фьючерс
type Futures struct {
	// AssetCode Торговый код базового актива
	AssetCode string `json:"asset_code"`

	// AssetType Тип базового актива
	AssetType AssetType `json:"asset_type"`

	// ExpirationDate Дата погашения
	ExpirationDate Date `json:"expiration_date"`

	// FuturesCode Краткий код фьючерса
	FuturesCode string `json:"futures_code"`
}

// IndicatorGraph Графики индикатора
type IndicatorGraph struct {
	// Now На текущую дату
	Now []IndicatorGraphPoint `json:"now"`

	// OnExpiration На дату исполнения
	OnExpiration []IndicatorGraphPoint `json:"on_expiration"`

	// OnWhatIf С условием "что если"
	OnWhatIf *[]IndicatorGraphPoint `json:"on_what_if,omitempty"`
}

// IndicatorGraphPoint Точка на графике индикатора
type IndicatorGraphPoint struct {
	// UnderlyingPrice Цена БА, пунктов
	UnderlyingPrice float64 `json:"underlying_price"`

	// Value Значение индикатора
	Value float64 `json:"value"`
}

// IndicatorType Вид индикатора
type IndicatorType string

// InitialMarginPosition Позиция для расчета гарантийного обеспечения
type InitialMarginPosition struct {
	// NettedIm Признак неттирования гарантийного обеспечения
	NettedIm *bool `json:"netted_im,omitempty"`

	// Price Цена покупки
	Price float64 `json:"price"`

	// Quantity Количество покупки (отрицательное число - продажа)
	Quantity int `json:"quantity"`

	// Secid Торговый код фьючерса или опциона
	Secid string `json:"secid"`
}

// Option Опцион
type Option struct {
	// AssetCode Торговый код базового актива
	AssetCode string `json:"asset_code"`

	// AssetType Тип базового актива
	AssetType AssetType `json:"asset_type"`

	// ExpirationDate Дата исполнения
	ExpirationDate Date `json:"expiration_date"`

	// FuturesCode Код фьючерса, если применимо
	FuturesCode *string `json:"futures_code,omitempty"`

	// OptionType Тип опциона (call, put)
	OptionType OptionType `json:"option_type"`

	// Secid Торговый код опциона
	Secid string `json:"secid"`

	// SeriesType Вид серии опционов
	SeriesType OptionSeriesType `json:"series_type"`

	// Strike Cтрайк
	Strike float64 `json:"strike"`
}

// OptionBoard Доска опционов
type OptionBoard struct {
	// Call Опционы на покупку
	Call []OptionBoardRow `json:"call"`

	// Put Опционы на продажу
	Put []OptionBoardRow `json:"put"`
}

// OptionBoardRow Опцион с индикаторами
type OptionBoardRow struct {
	// Bid Спрос, пунктов, руб
	Bid *float64 `json:"bid,omitempty"`

	// Delta Дельта, пунктов
	Delta *float64 `json:"delta,omitempty"`

	// Gamma Гамма, пунктов
	Gamma *float64 `json:"gamma,omitempty"`

	// IntrinsicValue Внутренняя стоимость, пунктов
	IntrinsicValue *float64 `json:"intrinsic_value,omitempty"`

	// Last Последняя цена, пунктов
	Last *float64 `json:"last,omitempty"`

	// Numtrades Количество сделок
	Numtrades *int `json:"numtrades,omitempty"`

	// Offer Предложение, пунктов, руб
	Offer *float64 `json:"offer,omitempty"`

	// Rho Ро, пунктов
	Rho *float64 `json:"rho,omitempty"`

	// Secid Торговый код опциона
	Secid string `json:"secid"`

	// Strike Страйк, пунктов
	Strike float64 `json:"strike"`

	// Theorprice Теоретическая цена опциона, пунктов
	Theorprice *float64 `json:"theorprice,omitempty"`

	// TheorpriceRub Теоретическая цена опциона, руб
	TheorpriceRub *float64 `json:"theorprice_rub,omitempty"`

	// Theta Тета, пунктов
	Theta *float64 `json:"theta,omitempty"`

	// TimedValue ВременнАя стоимость, пунктов
	TimedValue *float64 `json:"timed_value,omitempty"`

	// Vega Вега, пунктов
	Vega *float64 `json:"vega,omitempty"`

	// Volatility Волатильность, процентов
	Volatility *float64 `json:"volatility,omitempty"`
}

// OptionBrief Расчетные параметры для выбранного опциона
type OptionBrief struct {
	// DaysUntilExpiring Дней до исполнения
	DaysUntilExpiring int `json:"days_until_expiring"`

	// Delta Дельта, пунктов
	Delta *float64 `json:"delta,omitempty"`

	// ExpiringDate Дата исполнения опциона, формат YYYY-MM-DD
	ExpiringDate Date `json:"expiring_date"`

	// Fee Комиссия, руб
	Fee *float64 `json:"fee,omitempty"`

	// Gamma Гамма, пунктов
	Gamma *float64 `json:"gamma,omitempty"`

	// Lastprice Последняя цена базового актива, руб
	Lastprice float64 `json:"lastprice"`

	// Rho Ро, пунктов
	Rho *float64 `json:"rho,omitempty"`

	// Secid Торговый код опциона
	Secid string `json:"secid"`

	// Settleprice Расчетная цена БА, руб
	Settleprice float64 `json:"settleprice"`

	// Theorprice Теор цена, пунктов
	Theorprice float64 `json:"theorprice"`

	// Theta Тета, пунктов
	Theta *float64 `json:"theta,omitempty"`

	// UnderlyingAsset Базовый актив
	UnderlyingAsset string `json:"underlying_asset"`

	// UnderlyingPrice Цена БА, пунктов
	UnderlyingPrice float64 `json:"underlying_price"`

	// UnderlyingType Тип базового актива
	UnderlyingType AssetType `json:"underlying_type"`

	// Vega Вега, пунктов
	Vega *float64 `json:"vega,omitempty"`

	// Volatility Волатильность, процентов
	Volatility float64 `json:"volatility"`
}

// OptionPortfolio Опционный портфель
type OptionPortfolio struct {
	// AssetCode Торговый код базового актива
	AssetCode string `json:"asset_code"`

	// AssetType Тип базового актива
	AssetType *AssetType `json:"asset_type,omitempty"`

	// Positions Моделируемые позиции
	Positions []SimulatedPosition `json:"positions"`

	// WhatIf Условие "что если"
	WhatIf *WhatIfCondition `json:"what_if,omitempty"`
}

// OptionSeries Серия опциона с сумарными показателями по входящим в серию опционам
type OptionSeries struct {
	// AssetCode Торговый код базового актива
	AssetCode string `json:"asset_code"`

	// AssetType Тип базового актива
	AssetType AssetType `json:"asset_type"`

	// Call Суммарно для call-опционов
	Call *OptionSeriesTotals `json:"call,omitempty"`

	// CentralStrike Центральный страйк
	CentralStrike float64 `json:"central_strike"`

	// ExpirationDate Дата погашения
	ExpirationDate Date `json:"expiration_date"`

	// FuturesCode Код фьючерса, если применимо
	FuturesCode *string `json:"futures_code,omitempty"`

	// OptionseriesCode Код серии опциона
	OptionseriesCode string `json:"optionseries_code"`

	// Put Суммарно для put-опционов
	Put *OptionSeriesTotals `json:"put,omitempty"`

	// SeriesType Вид серии опционов
	SeriesType OptionSeriesType `json:"series_type"`

	// Updatetime Время обновления информации
	Updatetime *DateTime `json:"updatetime,omitempty"`
}

// OptionSeriesTotals Суммарные показатели
type OptionSeriesTotals struct {
	// Oichange Изменение числа открытых позиций
	Oichange *int `json:"oichange,omitempty"`

	// Openposition Число открытых позиций
	Openposition *int `json:"openposition,omitempty"`

	// VolumeContracts Объем контрактов
	VolumeContracts *int `json:"volume_contracts,omitempty"`

	// VolumeRub Объем в рублях
	VolumeRub *float64 `json:"volume_rub,omitempty"`
}

// OptionSeriesType Тип серии опциона
type OptionSeriesType string

// OptionType Тип опциона
type OptionType string

// SimulatedPosition Моделируемая позиция
type SimulatedPosition struct {
	// NettedIm Признак неттирования гарантийного обеспечения
	NettedIm *bool `json:"netted_im,omitempty"`

	// Price Цена покупки
	Price *float64 `json:"price,omitempty"`

	// Quantity Количество покупки (отрицательное число - продажа)
	Quantity int `json:"quantity"`

	// Secid Торговый код
	Secid string `json:"secid"`

	// Type Вид торгового инструмента
	Type *SimulatedPositionType `json:"type,omitempty"`

	// Volatility Волатильность, процентов
	Volatility *float64 `json:"volatility,omitempty"`
}

// SimulatedPositionType Вид тикера в моделируемой позиции
type SimulatedPositionType string

// VolatilityGraphPoint Точка на графике волатильности
type VolatilityGraphPoint struct {
	// Strike Страйк, пунктов
	Strike float64 `json:"strike"`

	// Volatility Волатильность, процентов
	Volatility float64 `json:"volatility"`
}

// WhatIfCondition Условие 'что если'
type WhatIfCondition struct {
	// DateOfCalculation Дата рассчета
	DateOfCalculation *Date `json:"date_of_calculation,omitempty"`

	// DeltaSigma Смещение волатильности, процентов
	DeltaSigma *float64 `json:"delta_sigma,omitempty"`
}

// AssetsAssetsGetParams defines parameters for AssetsAssetsGet.
type AssetsAssetsGetParams struct {
	// AssetType Тип базового актива
	AssetType *AssetType `form:"asset_type,omitempty" json:"asset_type,omitempty"`

	// AssetSubtype Подтип базового актива для фьючерсов
	AssetSubtype *AssetSubtype `form:"asset_subtype,omitempty" json:"asset_subtype,omitempty"`

	// Query Фильтр названия БА
	Query *string `form:"query,omitempty" json:"query,omitempty"`
}

// AssetDetailAssetsAssetCodeGetParams defines parameters for AssetDetailAssetsAssetCodeGet.
type AssetDetailAssetsAssetCodeGetParams struct {
	// AssetType Тип базового актива
	AssetType *AssetType `form:"asset_type,omitempty" json:"asset_type,omitempty"`
}

// AllFuturesAssetsAssetCodeFuturesGetParams defines parameters for AllFuturesAssetsAssetCodeFuturesGet.
type AllFuturesAssetsAssetCodeFuturesGetParams struct {
	// ExpirationDate Дата погашения
	ExpirationDate *Date `form:"expiration_date,omitempty" json:"expiration_date,omitempty"`
}

// AllOptionsAssetsAssetCodeOptionsGetParams defines parameters for AllOptionsAssetsAssetCodeOptionsGet.
type AllOptionsAssetsAssetCodeOptionsGetParams struct {
	// AssetType Тип базового актива
	AssetType *AssetType `form:"asset_type,omitempty" json:"asset_type,omitempty"`

	// ExpirationDate Дата исполнения
	ExpirationDate *Date `form:"expiration_date,omitempty" json:"expiration_date,omitempty"`

	// SeriesType Вид серии опционов
	SeriesType *OptionSeriesType `form:"series_type,omitempty" json:"series_type,omitempty"`

	// Strike Cтрайк
	Strike *float64 `form:"strike,omitempty" json:"strike,omitempty"`

	// OptionType Тип опциона (call, put)
	OptionType *OptionType `form:"option_type,omitempty" json:"option_type,omitempty"`
}

// BriefAssetsAssetCodeOptionsSecidGetParams defines parameters for BriefAssetsAssetCodeOptionsSecidGet.
type BriefAssetsAssetCodeOptionsSecidGetParams struct {
	// AssetType Тип базового актива
	AssetType *AssetType `form:"asset_type,omitempty" json:"asset_type,omitempty"`

	// DaysUntilExpiring Дней до исполнения
	DaysUntilExpiring *int `form:"days_until_expiring,omitempty" json:"days_until_expiring,omitempty"`

	// UnderlyingPrice Цена базового актива, рублей
	UnderlyingPrice *float64 `form:"underlying_price,omitempty" json:"underlying_price,omitempty"`

	// Volatility Волатильность IV, процентов
	Volatility *float64 `form:"volatility,omitempty" json:"volatility,omitempty"`
}

// AllOptionSeriesAssetsAssetCodeOptionseriesGetParams defines parameters for AllOptionSeriesAssetsAssetCodeOptionseriesGet.
type AllOptionSeriesAssetsAssetCodeOptionseriesGetParams struct {
	// AssetType Тип базового актива
	AssetType *AssetType `form:"asset_type,omitempty" json:"asset_type,omitempty"`
}

// OptionSeriesAssetsAssetCodeOptionseriesOptionseriesCodeGetParams defines parameters for OptionSeriesAssetsAssetCodeOptionseriesOptionseriesCodeGet.
type OptionSeriesAssetsAssetCodeOptionseriesOptionseriesCodeGetParams struct {
	// AssetType Тип базового актива
	AssetType *AssetType `form:"asset_type,omitempty" json:"asset_type,omitempty"`
}

// OptionboardAssetsAssetCodeOptionseriesOptionseriesCodeOptionboardGetParams defines parameters for OptionboardAssetsAssetCodeOptionseriesOptionseriesCodeOptionboardGet.
type OptionboardAssetsAssetCodeOptionseriesOptionseriesCodeOptionboardGetParams struct {
	// AssetType Тип базового актива
	AssetType *AssetType `form:"asset_type,omitempty" json:"asset_type,omitempty"`

	// Rows Количество строк от центрального страйка
	Rows *int `form:"rows,omitempty" json:"rows,omitempty"`
}

// OptionsAssetsAssetCodeOptionseriesOptionseriesCodeOptionsGetParams defines parameters for OptionsAssetsAssetCodeOptionseriesOptionseriesCodeOptionsGet.
type OptionsAssetsAssetCodeOptionseriesOptionseriesCodeOptionsGetParams struct {
	// AssetType Тип базового актива
	AssetType *AssetType `form:"asset_type,omitempty" json:"asset_type,omitempty"`

	// Strike Cтрайк
	Strike *int `form:"strike,omitempty" json:"strike,omitempty"`

	// OptionType Тип опциона (call, put)
	OptionType *OptionType `form:"option_type,omitempty" json:"option_type,omitempty"`
}

// VolatilityGraphAssetsAssetCodeOptionseriesOptionseriesCodeVolatilityGraphGetParams defines parameters for VolatilityGraphAssetsAssetCodeOptionseriesOptionseriesCodeVolatilityGraphGet.
type VolatilityGraphAssetsAssetCodeOptionseriesOptionseriesCodeVolatilityGraphGetParams struct {
	// AssetType Тип базового актива
	AssetType *AssetType `form:"asset_type,omitempty" json:"asset_type,omitempty"`
}

// InitialMarginPortfolioInitialMarginPostJSONBody defines parameters for InitialMarginPortfolioInitialMarginPost.
type InitialMarginPortfolioInitialMarginPostJSONBody = []InitialMarginPosition

// PortfolioPortfolioPostJSONRequestBody defines body for PortfolioPortfolioPost for application/json ContentType.
type PortfolioPortfolioPostJSONRequestBody = OptionPortfolio

// GraphPortfolioGraphIndicatorPostJSONRequestBody defines body for GraphPortfolioGraphIndicatorPost for application/json ContentType.
type GraphPortfolioGraphIndicatorPostJSONRequestBody = OptionPortfolio

// InitialMarginPortfolioInitialMarginPostJSONRequestBody defines body for InitialMarginPortfolioInitialMarginPost for application/json ContentType.
type InitialMarginPortfolioInitialMarginPostJSONRequestBody = InitialMarginPortfolioInitialMarginPostJSONBody
